In [3]:
height = [72,68,69,64,72,72] # in inches
height_m = [0] * 6

for i in range(len(height)):
    height_m[i] = height[i] * 0.0254

In [17]:
import numpy as np
height = [72,68,69,64,72,72] # in inches
np_height = np.array(height)
np_height

array([72, 68, 69, 64, 72, 72])

In [22]:
# Convert np_height to meters
np_height_m = np_height * 0.0254
np_height_m

array([1.8288, 1.7272, 1.7526, 1.6256, 1.8288, 1.8288])

In [23]:
###############################################################
python_list1 = [2,4,6]
python_list2 = [1,3,5]

numpy_list1 = np.array(python_list1)
numpy_list2 = np.array(python_list2)

In [24]:
python_list1 + python_list2

[2, 4, 6, 1, 3, 5]

In [25]:
numpy_list1 + numpy_list2

array([ 3,  7, 11])

In [27]:
###############################################################
numbers = [10,15,20,35]
numbers2 = [10.0,15.1,19.5]

x = np.array(numbers)
y = np.array(numbers, dtype = "float")
y

array([10., 15., 20., 35.])

In [28]:
x.dtype

dtype('int32')

In [29]:
y.dtype

dtype('float64')

In [30]:
age = np.array([18,23,89,11,35,37,26,52,76])
age

array([18, 23, 89, 11, 35, 37, 26, 52, 76])

In [31]:
age[2]

89

In [35]:
age[2:5]

array([89, 11, 35])

In [37]:
age[:3]

array([18, 23, 89])

In [43]:
age[-3:]

array([26, 52, 76])

In [44]:
age[::-1]

array([76, 52, 26, 37, 35, 11, 89, 23, 18])

In [45]:
################################################################
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [47]:
np.arange(2,10.1,2)

array([ 2.,  4.,  6.,  8., 10.])

In [48]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [49]:
np.arange(-6,3)

array([-6, -5, -4, -3, -2, -1,  0,  1,  2])

In [52]:
np.arange(5,0,-1)

array([5, 4, 3, 2, 1])

In [53]:
age

array([18, 23, 89, 11, 35, 37, 26, 52, 76])

In [54]:
age>35

array([False, False,  True, False, False,  True, False,  True,  True])

In [56]:
age[age>35]

array([89, 37, 52, 76])

In [ ]:
#35 < age < 55

In [59]:
age[(age>35) & (age<55)]

array([37, 52])

In [ ]:
# &: and
# |: or
# ~: not

In [62]:
np.zeros(6) # generate n zeros and fills an array

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# 9-12-2022
##############################################################

In [2]:
import numpy as np

height = [72,68,69,68,64,72,72]
weight = [200,165,160,135,120,162,190]
metrics = np.array([height,weight])
metrics

array([[ 72,  68,  69,  68,  64,  72,  72],
       [200, 165, 160, 135, 120, 162, 190]])

In [3]:
metrics.shape

(2, 7)

In [4]:
metrics[0,4]

64

In [5]:
metrics[0][4]

64

In [7]:
metrics[:,0:2] # all rows, first columns

array([[ 72,  68],
       [200, 165]])

In [8]:
metrics[0,:] # first row

array([72, 68, 69, 68, 64, 72, 72])

In [12]:
x = np.arange(1,10)
x.reshape(3,3) # reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10).reshape(3,3) # same thing

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# resize() # overwrites the object
x = np.arange(1,10)
x.resize(3,3) # resize

In [15]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
B = x.reshape(-1,3)
B

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [18]:
C = x.reshape(5,-1)
C

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [21]:
arr = np.array([[14,17,12,33,44],[15,6,27,8,19],[23,2,54,1,4]])
arr

array([[14, 17, 12, 33, 44],
       [15,  6, 27,  8, 19],
       [23,  2, 54,  1,  4]])

In [22]:
arr.shape

(3, 5)

In [23]:
np.sum(arr,axis=0) # 0 gives an output that resembles to a row aka "column sum"

array([52, 25, 93, 42, 67])

In [24]:
np.sum(arr,axis=1) # 1 give you ouput that resembles to a column aka "row sum"

array([120,  75,  84])

In [28]:
np.round(np.mean(arr,axis=0),2) # column means, rounded

array([17.33,  8.33, 31.  , 14.  , 22.33])

In [26]:
np.mean(arr,axis=1) # row means

array([24. , 15. , 16.8])

In [ ]:
#####################################

In [34]:
data = np.array([2, np.nan, -1, 3])
data

array([ 2., nan, -1.,  3.])

In [35]:
data.dtype

dtype('float64')

In [36]:
np.sum(data)

nan

In [37]:
np.nansum(data)

4.0

In [39]:
np.isnan(data) # check if element is missing

array([False,  True, False, False])

In [45]:
# broadcasting
metrics_transposed = metrics.T
metrics_transposed # first column is height (inches) second col is weight (lbs)

array([[ 72, 200],
       [ 68, 165],
       [ 69, 160],
       [ 68, 135],
       [ 64, 120],
       [ 72, 162],
       [ 72, 190]])

In [52]:
multiplier = [0.0254, 0.4535]
multiplier

[0.0254, 0.4535]

In [53]:
metrics_transposed * multiplier # broadcasting worked!
# numpy stretched, the 1x2 array into a 7x2 matrix and operation worked!

array([[ 1.8288, 90.7   ],
       [ 1.7272, 74.8275],
       [ 1.7526, 72.56  ],
       [ 1.7272, 61.2225],
       [ 1.6256, 54.42  ],
       [ 1.8288, 73.467 ],
       [ 1.8288, 86.165 ]])

In [54]:
a = np.array([1,2,3])
b = np.array([2,2,2])

a*b

array([2, 4, 6])

In [55]:
a = np.array([1,2,3])
b = 2

a*b

array([2, 4, 6])

In [57]:
#######
X = np.array([[[10,20,30],[40,50,60]], [[15,25,35],[45,55,65]], [[70,80,90],[75,85,95]]])

In [58]:
X

array([[[10, 20, 30],
        [40, 50, 60]],

       [[15, 25, 35],
        [45, 55, 65]],

       [[70, 80, 90],
        [75, 85, 95]]])

In [60]:
X[2,1,2] # first number is the matrix position, second is row, third is column

95

In [63]:
a=np.ones((2,5,1,8,4))
b=np.ones((3,1,4))
c=np.ones((5,1,8,1))
a

array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
    

In [ ]:
a.shape # huge!

In [67]:
X = a*b*c
X

array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          

In [66]:
X.shape

(2, 5, 3, 8, 4)